$color = rgba(250, 250, 250, 1)
$inner_color = rgba(250, 250, 250, 0.66)
$outer_color = rgba(166, 38, 164, 1)
$font_color = rgba(9, 10, 11, 1)
$placeholder_color = rgba(9, 10, 11, 0.7)
$check_color = rgba(1, 132, 188, 1)
