background            #fafafa
foreground            #090a0b

# black
color0  #fafafa
color8  #e5e5e6

# red
color1  #e45649
color9  #e45649

# green
color2  #50a14f
color10 #50a14f

# yellow
color3  #c18401
color11 #c18401

# blue
color4  #4078f2
color12 #4078f2

# magenta
color5  #a626a4
color13 #a626a4

#cyan
color6  #0184bc
color14 #0184bc

#white
color7  #383a42
color15 #090a0b


